{% set name = "reprostim" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/reprostim-{{ version }}.tar.gz
  sha256: f735714a725998816617df9ab84c9e0f79e6749544b0ab1d27d0fd0c5672d6c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - reprostim = reprostim.cli.entrypoint:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=46.4.0
    - pip
    - hatchling
    - versioningit
  run:
    - python >={{ python_min }}
    - click >=8.1.7
    - click-didyoumean >=0.3.1
    - pydantic >=2.7.1
    - numpy >=1.26.4
    - qrcode >=8.0
    - opencv >=4.9.0
    - pyzbar =0.1.8

test:
  imports:
    - reprostim
  commands:
    - python -m pytest -vv tests
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - reedsolo >=1.7.0
    - scipy
  source_files:
    - tests

about:
  home: https://github.com/ReproNim/reprostim/
  summary: ReproStim is a video capture and recording suite for neuroimaging and psychology experiments
  license: MIT
  license_family: MIT
  license_file: LICENSES/MIT.txt

extra:
  recipe-maintainers:
    - yarikoptic
    - vmdocua
